name: Build-Curl
on:
  workflow_dispatch
permissions: {}
jobs:
  build-and-curl:
    runs-on: ubuntu-latest
    steps: 
    - name: get_code
      uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
    - name: docker build
      run: | 
        docker build -t pipeline-test .
    - name: docker_run
      run: | 
        docker run -d -p 8000:8000 -e 'DJANGO_SECRET_KEY=devpassworddontuseme' pipeline-test
    - name: curl_ftw
      run: |
        sleep 10
        curl -f http://localhost:8000/
